services:
  tor:
    build:
      context: .
      dockerfile_inline: |
        FROM debian:bullseye-slim
        RUN apt-get update && apt-get install -y tor && apt-get clean && rm -rf /var/lib/apt/lists/*
        RUN mkdir -p /var/lib/tor/hidden_service && chown -R debian-tor:debian-tor /var/lib/tor/hidden_service/ && \
            chmod 700 /var/lib/tor/hidden_service/ && echo "HiddenServiceDir /var/lib/tor/hidden_service/" > /etc/tor/torrc && \
            echo "HiddenServicePort 80 nginx:80" >> /etc/tor/torrc
        USER debian-tor
        CMD tor -f /etc/tor/torrc
    volumes:
      - tor_data:/var/lib/tor/hidden_service
    restart: unless-stopped
    networks:
      - net

  nginx:
    depends_on: [tor]
    image: nginx:alpine
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
      - tor_data:/tor_data:ro
    command: sh -c "apk add --no-cache curl && /start.sh"
    configs:
      - source: nginx_script
        target: /start.sh
        mode: 0755
    restart: unless-stopped
    networks:
      - net

networks:
  net:

volumes:
  tor_data:

configs:
  nginx_script:
    content: |
      #!/bin/sh
      echo '<html><body><h1>Dstack TEE Tor Onion Service</h1>' > /usr/share/nginx/html/index.html
      while [ ! -f /tor_data/hostname ]; do sleep 1; done
      addr=$$(cat /tor_data/hostname)
      echo "<p>$$addr</p>" >> /usr/share/nginx/html/index.html
      hash=$$(echo -n "$$addr" | sha256sum)
      payload="{\"report_data\":\"$$(echo -n $$hash | od -A n -t x1 | tr -d ' \n')\"}"
      attest=$$(curl -sX POST --unix-socket /var/run/tappd.sock -d "$$payload" http://localhost/prpc/Tappd.TdxQuote?json)
      echo "<pre style='white-space: pre-wrap;'>$$attest</pre></body></html>" >> /usr/share/nginx/html/index.html
      echo "Serving at $$addr"
      exec nginx -g 'daemon off;'
