blank_issues_enabled: false
contact_links:
  - name: 💬 Community Discussion
    url: https://t.me/+UO4bS4jflr45YmUx
    about: Join our Telegram community for general questions and discussions
  - name: 🔒 Security Vulnerability
    url: mailto:dstack@phala.network
    about: Report security vulnerabilities privately via email
  - name: 📖 Documentation
    url: https://docs.phala.network/dstack
    about: Check the official Dstack documentation
  - name: ❓ GitHub Discussions
    url: https://github.com/Dstack-TEE/dstack-examples/discussions
    about: Ask questions and discuss ideas with the community
