name: Documentation Issue
description: Report an issue with documentation
title: "[DOCS] "
labels: ["documentation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Please describe the issue below.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs attention?
      options:
        - Example README
        - Main README
        - Contributing Guidelines
        - Security Documentation
        - Code Comments
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation issue located?
      placeholder: e.g., "attestation/configid-based/README.md", "CONTRIBUTING.md", etc.
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of documentation issue is this?
      options:
        - Incorrect Information
        - Missing Information
        - Unclear Instructions
        - Broken Links
        - Outdated Content
        - Typo/Grammar
        - Formatting Issue
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Describe the documentation issue
      placeholder: What's wrong with the documentation?
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: Current Content (if applicable)
      description: Copy the current problematic content
      placeholder: Paste the current content here...
      render: markdown

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: How should this be corrected?
      placeholder: What should the content say instead?
      render: markdown

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional context that might help
      placeholder: |
        - How did you encounter this issue?
        - What were you trying to accomplish?
        - Any related issues?

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to submit a PR to fix this documentation issue
          required: false
