name: Example Submission
description: Submit a new example for review
title: "[EXAMPLE] "
labels: ["new-example", "needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing a new example! Please fill out this form to help us review your submission.

  - type: input
    id: example-name
    attributes:
      label: Example Name
      description: What is the name of your example?
      placeholder: e.g., "secure-file-storage"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Example Description
      description: What does your example demonstrate?
      placeholder: |
        Provide a clear description of:
        - What the example does
        - What Dstack/TEE features it showcases
        - What problem it solves
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Example Category
      description: Which category does your example fit into?
      options:
        - Security & Attestation
        - Networking & Domains
        - Development Tools
        - Advanced Use Cases
        - Blockchain Integration
        - Other
    validations:
      required: true

  - type: dropdown
    id: difficulty
    attributes:
      label: Difficulty Level
      description: What's the complexity level of this example?
      options:
        - Beginner
        - Intermediate
        - Advanced
    validations:
      required: true

  - type: textarea
    id: technologies
    attributes:
      label: Technologies Used
      description: List the main technologies, frameworks, or tools used
      placeholder: |
        - Docker/Docker Compose
        - Programming languages
        - Frameworks
        - External services
        - etc.
      render: markdown
    validations:
      required: true

  - type: textarea
    id: prerequisites
    attributes:
      label: Prerequisites
      description: What are the prerequisites for running this example?
      placeholder: |
        - Required knowledge
        - Software dependencies
        - Hardware requirements
        - Account setups (if any)
      render: markdown

  - type: textarea
    id: security-features
    attributes:
      label: Security Features
      description: What TEE/security features does this example demonstrate?
      placeholder: |
        - Remote attestation
        - Secure communication
        - Secret management
        - Privacy preservation
        - etc.
      render: markdown

  - type: checkboxes
    id: checklist
    attributes:
      label: Submission Checklist
      description: Please confirm you've completed these items
      options:
        - label: I've followed the example structure guidelines from CONTRIBUTING.md
          required: true
        - label: I've included a comprehensive README.md
          required: true
        - label: I've tested the example and it works correctly
          required: true
        - label: I've included necessary environment variable examples
          required: true
        - label: I've documented security considerations
          required: true
        - label: I've followed security best practices
          required: true
        - label: My example doesn't contain hardcoded secrets
          required: true

  - type: textarea
    id: testing
    attributes:
      label: Testing Information
      description: How have you tested this example?
      placeholder: |
        - Testing environments used
        - Test scenarios covered
        - Known limitations
        - Troubleshooting tested
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Notes
      description: Any additional information for reviewers
      placeholder: |
        - Special considerations
        - Future improvements planned
        - Related examples
        - etc.
